# Generated by Django 3.1.6 on 2021-06-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likeCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
