# Generated by Django 3.1.6 on 2021-07-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulecollection',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='rulecollection',
            name='num_subscribers',
            field=models.IntegerField(default=0),
        ),
    ]
