# Generated by Django 3.1.6 on 2021-08-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='case_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rule',
            name='spell_variants',
            field=models.BooleanField(default=True),
        ),
    ]
