# Generated by Django 3.1.6 on 2021-06-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_auto_20210602_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='thread_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
