# Generated by Django 3.1.6 on 2021-06-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_comment_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulecollection',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
