# Generated by Django 3.1.6 on 2021-08-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_auto_20210806_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulecollection',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
