# Generated by Django 3.1.6 on 2021-06-07 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0007_rulecollection_is_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulecollection',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube.channel'),
        ),
    ]
