# Generated by Django 3.1.6 on 2022-04-26 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0007_auto_20210826_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchedComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('span', models.TextField()),
                ('applied_date', models.DateTimeField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.comment')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.rule')),
            ],
            options={
                'unique_together': {('rule', 'comment')},
            },
        ),
    ]
