# Generated by Django 3.1.6 on 2021-06-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0008_auto_20210607_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='exception_phrase',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
